### ISSUE TITLE
The site is build but no public directory is present

### ISSUE THREAD

**Issue by dimensi0n** [chabad360/hugo-actions#2]
Here is my repository : https://github.com/open-incubator/wiki
Here is my workflow file : https://github.com/open-incubator/wiki/blob/master/.github/workflows/main.yml

As you can see the action passed but no site is generated in the repository.
What did I make wrong ?

**Comment by chabad360** [comment]
The action does not commit any files, it's meant to be used in a pipeline to generate the site, and then be published (separately) as part of the workflow.

So basically if you added an action to run `ls .`, the `public` folder would be present. But that doesn't effect the actual repository at all.
